EEP-RAN-176: Policies updates do not take the effect after node restart unless you run configure.sh script (2.4.0)
RESOLVED for 2.4.0, origin commit: 72f3a0aaea59ef23c510ea439879f0810601a618
Automerge (mergetool: kdiff3), no manual interference

diff --git a/embeddedwebserver/scripts/ranger-admin-initd b/embeddedwebserver/scripts/ranger-admin-initd
--- a/embeddedwebserver/scripts/ranger-admin-initd
+++ b/embeddedwebserver/scripts/ranger-admin-initd
@@ -33,49 +33,49 @@ if [ ! -d "/var/run/ranger" ]; then
   chmod -R 775 /var/run/ranger
 fi
 
-pid=`ps -ef | grep java | grep -- '-Dproc_rangeradmin' | grep -v grep | awk '{ print $2 }'`
-
-case $1 in
-start)
-	if [ "${pid}" != "" ]
-	then
-		echo "Ranger Admin Service is already running"
-		exit 1
-	else
-		echo "Starting Apache Ranger Admin."
-		/bin/su --login  $LINUX_USER -c "${BIN_PATH}/${MOD_NAME} start"
-	fi
-	;;
-stop)
-	if [ "${pid}" != "" ]
-	then
-		echo "Stopping Apache Ranger Admin."
-		/bin/su --login  $LINUX_USER -c "${BIN_PATH}/${MOD_NAME} stop"
-	else
-		echo "Ranger Admin Service is NOT running"
-		exit 1
-	fi
-	;;
-restart)
-	if [ "${pid}" != "" ]
-	then
-		echo "Stopping Apache Ranger Admin."
-		/bin/su --login  $LINUX_USER -c "${BIN_PATH}/${MOD_NAME} stop"
-		sleep 10
-	fi
-	echo "Starting Apache Ranger Admin."
-	/bin/su --login  $LINUX_USER -c "${BIN_PATH}/${MOD_NAME} start"
-	;;
-status)
-	if [ "${pid}" != "" ]
-	then
-		echo "Ranger Admin Service is  running [pid={$pid}]"
-	else
-		echo "Ranger Admin Service is  NOT running." 
-
-	fi
-	;;
-*)
-	echo "Invalid argument [$1]; Only start|stop|restart|status are supported."
-    exit 1
-esac
+#pid=`ps -ef | grep java | grep -- '-Dproc_rangeradmin' | grep -v grep | awk '{ print $2 }'`
+#
+#case $1 in
+#start)
+#	if [ "${pid}" != "" ]
+#	then
+#		echo "Ranger Admin Service is already running"
+#		exit 1
+#	else
+#		echo "Starting Apache Ranger Admin."
+#		/bin/su --login  $LINUX_USER -c "${BIN_PATH}/${MOD_NAME} start"
+#	fi
+#	;;
+#stop)
+#	if [ "${pid}" != "" ]
+#	then
+#		echo "Stopping Apache Ranger Admin."
+#		/bin/su --login  $LINUX_USER -c "${BIN_PATH}/${MOD_NAME} stop"
+#	else
+#		echo "Ranger Admin Service is NOT running"
+#		exit 1
+#	fi
+#	;;
+#restart)
+#	if [ "${pid}" != "" ]
+#	then
+#		echo "Stopping Apache Ranger Admin."
+#		/bin/su --login  $LINUX_USER -c "${BIN_PATH}/${MOD_NAME} stop"
+#		sleep 10
+#	fi
+#	echo "Starting Apache Ranger Admin."
+#	/bin/su --login  $LINUX_USER -c "${BIN_PATH}/${MOD_NAME} start"
+#	;;
+#status)
+#	if [ "${pid}" != "" ]
+#	then
+#		echo "Ranger Admin Service is  running [pid={$pid}]"
+#	else
+#		echo "Ranger Admin Service is  NOT running."
+#
+#	fi
+#	;;
+#*)
+#	echo "Invalid argument [$1]; Only start|stop|restart|status are supported."
+#    exit 1
+#esac
diff --git a/unixauthservice/scripts/initd b/unixauthservice/scripts/initd
--- a/unixauthservice/scripts/initd
+++ b/unixauthservice/scripts/initd
@@ -32,63 +32,63 @@ if [ ! -d "/var/run/ranger" ]; then
   chmod -R 775 /var/run/ranger
 fi
 
-if [ -z "${USERSYNC_PID_DIR_PATH}" ]; then
-        USERSYNC_PID_DIR_PATH=/var/run/ranger
-fi
-if [ -z "${USERSYNC_PID_NAME}" ]
-then
-        USERSYNC_PID_NAME=usersync.pid
-fi
-pidf=${USERSYNC_PID_DIR_PATH}/${USERSYNC_PID_NAME}
-
-pid=""
-if [ -f ${pidf} ]
-then
-    pid=`cat $pidf` > /dev/null 2>&1
-else
-    pid=`ps -ef | grep java | grep -- '-Dproc_rangerusersync' | grep -v grep | awk '{ print $2 }'`
-fi
-
-case $1 in
-	start)
-	    if [ "${pid}" != "" ]
-	    then
-	        echo "Ranger Usersync Service is already running"
-		    exit 1
-		 else
-		 	echo "Starting Ranger Usersync."
-		    /bin/su --login  $LINUX_USER -c "${BIN_PATH}/${MOD_NAME} start"
-	    fi
-		;;
-	stop)
-	    if [ "${pid}" != "" ]
-        then
-            echo "Stopping Ranger Usersync."
-            /bin/su --login  $LINUX_USER -c "${BIN_PATH}/${MOD_NAME} stop"
-        else
-            echo "Ranger Usersync Service is NOT running"
-            exit 1
-        fi
-		;;
-	restart)
-        if [ "${pid}" != "" ]
-        then
-            echo "Stopping Ranger Usersync."
-            /bin/su --login  $LINUX_USER -c "${BIN_PATH}/${MOD_NAME} stop"
-            sleep 10
-        fi
-        echo "Starting Ranger Usersync."
-        /bin/su --login  $LINUX_USER -c "${BIN_PATH}/${MOD_NAME} start"
-		;;
-	status)
-        if [ "${pid}" != "" ]
-        then
-            echo "Ranger Usersync Service is running [pid={$pid}]"
-        else
-            echo "Ranger Usersync Service is NOT running."
-        fi
-	 ;;
-	*)
-		echo "Invalid argument [$1]; Only start | stop | restart | status, are supported."
-		exit 1
-	esac
+#if [ -z "${USERSYNC_PID_DIR_PATH}" ]; then
+#        USERSYNC_PID_DIR_PATH=/var/run/ranger
+#fi
+#if [ -z "${USERSYNC_PID_NAME}" ]
+#then
+#        USERSYNC_PID_NAME=usersync.pid
+#fi
+#pidf=${USERSYNC_PID_DIR_PATH}/${USERSYNC_PID_NAME}
+#
+#pid=""
+#if [ -f ${pidf} ]
+#then
+#    pid=`cat $pidf` > /dev/null 2>&1
+#else
+#    pid=`ps -ef | grep java | grep -- '-Dproc_rangerusersync' | grep -v grep | awk '{ print $2 }'`
+#fi
+#
+#case $1 in
+#	start)
+#	    if [ "${pid}" != "" ]
+#	    then
+#	        echo "Ranger Usersync Service is already running"
+#		    exit 1
+#		 else
+#		 	echo "Starting Ranger Usersync."
+#		    /bin/su --login  $LINUX_USER -c "${BIN_PATH}/${MOD_NAME} start"
+#	    fi
+#		;;
+#	stop)
+#	    if [ "${pid}" != "" ]
+#        then
+#            echo "Stopping Ranger Usersync."
+#            /bin/su --login  $LINUX_USER -c "${BIN_PATH}/${MOD_NAME} stop"
+#        else
+#            echo "Ranger Usersync Service is NOT running"
+#            exit 1
+#        fi
+#		;;
+#	restart)
+#        if [ "${pid}" != "" ]
+#        then
+#            echo "Stopping Ranger Usersync."
+#            /bin/su --login  $LINUX_USER -c "${BIN_PATH}/${MOD_NAME} stop"
+#            sleep 10
+#        fi
+#        echo "Starting Ranger Usersync."
+#        /bin/su --login  $LINUX_USER -c "${BIN_PATH}/${MOD_NAME} start"
+#		;;
+#	status)
+#        if [ "${pid}" != "" ]
+#        then
+#            echo "Ranger Usersync Service is running [pid={$pid}]"
+#        else
+#            echo "Ranger Usersync Service is NOT running."
+#        fi
+#	 ;;
+#	*)
+#		echo "Invalid argument [$1]; Only start | stop | restart | status, are supported."
+#		exit 1
+#	esac
